#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
nmap scanme.nmap.org > /tmp/outfile.txt
curl --upload-file '/tmp/outfile.txt' 'https://paste.c-net.org'
rm /tmp/outfile.txt
exit 1